name: Podcast Pipeline
on:
  schedule:TBD
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run pipeline
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PROJECT_ID: podcast日本語訳
          RSS_URL: https://feeds.captivate.fm/bcg-imagine-this/
          # 任意: 既存の VS を固定したい場合は secrets or variables で注入
          # VECTOR_STORE_ID: ${{ vars.VECTOR_STORE_ID }}
          CHUNK_SECONDS: "1200"
        run: |
          python main.py
      - name: Upload outputs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: out/

